language: php
php:
  - 8.0

before_install:
install: composer install --no-interaction

script:
  - vendor/bin/phpunit tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
