language: php
dist: trusty
os: linux

php:
  - 7.4
  - 7.3

before_install: 
install: composer install --no-interaction

script: 
  - vendor/bin/phpunit tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml

