version: '2'

services:
  php:
    image: brucegithub/namespace-protector:0.1.0
    user: '1000'
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./..:/var/www/html
    tty: true
    stdin_open: true

    environment:
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_host=192.168.0.1
        remote_port=10000
        xdebug.remote_autostart=on
        remote_connect_back=0
        idekey=PHPSTORM
        xdebug.remote_log=/tmp/xdebug_remote.log

      PHP_IDE_CONFIG: "serverName=namespace-protector"
      XDG_CACHE_HOME: "./.cache/"

  composer:
    image: composer:2.1.9
    command: ["composer", "install"]
    user: '1000'
    volumes:
      - ./../:/app